### ISSUE TITLE
Station signs

### ISSUE THREAD

**Issue by Dim67** [s4t4n/FS22_RandomFuelsPrices#1]
In the screenshots there are gas-station billboards that show the dynamic prices, but they are not included in the mod. Where do I get those signs?

**Comment by Dim67** [comment]
I placed a gas station on my map, but there is no menu anywhere.

**Comment by SbSh-DNA-ModDing** [comment]
this displays what are seen in the screenshots, will coming soon.
I just waiting for permission of an company name to use a name.
But I can make it as Lizard if you want.

does show your display all the real price via a script too ?

**Comment by SbSh-DNA-ModDing** [comment]
> I placed a gas station on my map, but there is no menu anywhere.

perhaps in the fillType.xml of the map, there is disable it.

`<fillType name="DIESEL" title="$l10n_fillType_diesel" showOnPriceTable="true" unitShort="$l10n_unit_literShort">`
then you have to set showOnPriceTable to true,
also you can do it for DEF, ELECTRICCHARGE, METHANE

**Comment by Dim67** [comment]
Ok I see, there is no mention in the description that the billboards arent in the mod yet. Might want to add that because I was looking for a placeable in the build menu, then looked in the mod file and noticed no i3d etc for the billboards.

**Comment by SbSh-DNA-ModDing** [comment]
Yes, I had to say that, I should have put that in the description.
I thought it would be faster with the permission, then it would be logical to see.
Sorry
