### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by talianagisan** [s4t4n/FS22_RandomFuelsPrices#2]
How does this mod interact with mods that change the base price of fuels such as real numbers. Will it do a percentage adjustment based off those mods, will it override it, will this mod be over ridden, or is it unknown how it might react in this case?

**Comment by SbSh-DNA-ModDing** [comment]
Hi, real number is unknown for me, but I think there it sets just once a static value - so that RFP override it at every random calculation.
The only little issue is with the "revamp" mod, the correction of the purchase prices - this should be disabled, than it works fine.
