### ISSUE TITLE
Server Multiplayer Problem

### ISSUE THREAD

**Issue by djdanby** [s4t4n/FS22_RandomFuelsPrices#3]
Hi.
I am writing to you because we have the problem on our server hosted map that your gas station displays do not show anything. We have your RandomFuelPrices Mod on the server as well. But we don't see any data at all on the displays. Even though we are very close to it.

I have then looked in singleplay if it works. Works. Then I started a multiplayer game myself (myself as server). Works as well. Only on a server that is hosted by a provider (Nitrado in our case), it unfortunately shows nothing. 
I have used in all tests, also everywhere the same mods that we also use on the server.

The map we play is called "Bergland" version 2.0.0.8 from Forbidden Mods.

Do you have any idea what the problem could be?

PS: And by the way. The ads in Single and Multi are displayed very late.  Only so at about 50 meters before the sign, you can see the values.

**Comment by SbSh-DNA-ModDing** [comment]
Hi, the time speed factor should not be 0 like pause, the display refresh every ingame minute.
The distance from which they are displayed depends on the graphics setting, just like with the weighing station.


![grafik](https://github.com/s4t4n/FS22_RandomFuelsPrices/assets/4678246/82b78a94-d6bf-4732-8d7d-23548adc878a)
